function Build-EmailHTML {
  <#
  .SYNOPSIS
      Builds HTML email content for restore completion notification
  
  .DESCRIPTION
      Creates a formatted HTML email with restore operation details,
      database information, and post-restore tasks.
  
  .PARAMETER Config
      The configuration hashtable
  
  .PARAMETER BackupFiles
      Hashtable containing backup file information
  
  .PARAMETER TestingMode
      Whether testing mode was enabled
  
  .PARAMETER StartTime
      When the restore operation started
  
  .PARAMETER EndTime
      When the restore operation completed
  
  .EXAMPLE
      $html = Build-EmailHTML -Config $config -BackupFiles $files -StartTime $start -EndTime $end
  #>
  [CmdletBinding()]
  param(
    [Parameter(Mandatory = $true)]
    [hashtable]$Config,
    
    [Parameter(Mandatory = $true)]
    [hashtable]$BackupFiles,
    
    [Parameter(Mandatory = $false)]
    [bool]$TestingMode = $false,
    
    [Parameter(Mandatory = $true)]
    [datetime]$StartTime,
    
    [Parameter(Mandatory = $true)]
    [datetime]$EndTime
  )

  $duration = $EndTime - $StartTime
  $durationString = "{0:hh\:mm\:ss}" -f $duration

  $html = @"
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #2e6c80; }
        h2 { color: #2e6c80; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin-top: 10px; }
        th { background-color: #2e6c80; color: white; padding: 10px; text-align: left; }
        td { border: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .success { color: green; font-weight: bold; }
        .warning { color: orange; font-weight: bold; }
        .info { background-color: #e7f3fe; padding: 15px; margin: 10px 0; border-left: 6px solid #2196F3; }
    </style>
</head>
<body>
    <h1>BusinessPlus Database Restore Completed</h1>
    
    <div class="info">
        <p><strong>Environment:</strong> $($Config.Environment)</p>
        <p><strong>Start Time:</strong> $($StartTime.ToString('yyyy-MM-dd HH:mm:ss'))</p>
        <p><strong>End Time:</strong> $($EndTime.ToString('yyyy-MM-dd HH:mm:ss'))</p>
        <p><strong>Duration:</strong> $durationString</p>
        <p><strong>Status:</strong> <span class="success">SUCCESS</span></p>
    </div>

    <h2>Databases Restored</h2>
    <table>
        <tr>
            <th>Database</th>
            <th>SQL Instance</th>
            <th>Backup File</th>
        </tr>
"@

  if ($BackupFiles.ASPNET) {
    $html += @"
        <tr>
            <td>$($Config.ASPNETdb)</td>
            <td>$($Config.SQLInstance)</td>
            <td>$($BackupFiles.ASPNET)</td>
        </tr>
"@
  }

  $html += @"
        <tr>
            <td>$($Config.SYSCATdb)</td>
            <td>$($Config.SQLInstance)</td>
            <td>$($BackupFiles.SYSCAT)</td>
        </tr>
        <tr>
            <td>$($Config.IFASdb)</td>
            <td>$($Config.IfasSQLInstance)</td>
            <td>$($BackupFiles.IFAS)</td>
        </tr>
    </table>

    <h2>Post-Restore Actions Completed</h2>
    <ul>
        <li>User accounts disabled (except manager codes: $($Config.ManagerCodes -join ', '))</li>
        <li>Email addresses updated to dummy values</li>
        <li>Non-essential workflows disabled</li>
        <li>NUUPAUSY display text updated with backup date</li>
"@

  if ($TestingMode) {
    $html += "        <li class='warning'>Testing Mode: Additional test accounts preserved</li>`n"
  }

  $html += @"
        <li>All servers rebooted</li>
    </ul>

    <h2>Next Steps</h2>
    <ol>
        <li>Verify BusinessPlus services are running on all servers</li>
        <li>Test application login with a manager account</li>
        <li>Verify email configuration points to test SMTP server</li>
        <li>Check dashboard accessibility (if applicable)</li>
        <li>Inform users that the $($Config.Environment) environment is ready for use</li>
    </ol>

    <h2>Server Information</h2>
    <table>
        <tr>
            <th>Server Type</th>
            <th>Servers</th>
        </tr>
        <tr>
            <td>Application Servers</td>
            <td>$($Config.Servers -join ', ')</td>
        </tr>
        <tr>
            <td>SQL Servers</td>
            <td>$($Config.SQLServers -join ', ')</td>
        </tr>
    </table>

    <hr>
    <p><em>This email was automatically generated by the BusinessPlus Database Restore process.</em></p>
</body>
</html>
"@

  return $html
}